version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-test
      MYSQL_PASSWORD: test
    ports:
      - '3307:3306'
